# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
   push: {tags:  ['*'] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: cd TileViewer.Plugin.Dotnet.RyoKoku && dotnet publish -p:PublishProfile=win_x64 && dotnet publish -p:PublishProfile=linux_x64
    - name: 7zip release
      run : 7z a -t7z -mx=9 TileViewer.Plugin.Dotnet.RyoKoku-x64_release.7z ./TileViewer.Plugin.Dotnet.RyoKoku/publish/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "TileViewer.Plugin.Dotnet.RyoKoku-x64_release.7z"
        bodyFile: ""
        token: ${{ secrets.GITHUB_TOKEN }}
